sudo: required
dist: xenial

addons:
    chrome: stable

language: php

php:
    - 7.3
    - 7.4

services:
    - memcached
    - mysql

notifications:
  email:
    - barryo@inex.ie

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql -u root -pnew_password -e 'CREATE DATABASE myapp_test CHARACTER SET = "utf8mb4" COLLATE = "utf8mb4_unicode_ci";'
  - mysql -u root -pnew_password -e 'GRANT ALL ON myapp_test.* TO travis@127.0.0.1 IDENTIFIED BY "";'
  - sudo apt-get update
  - "./data/travis-ci/setup_tests.sh"

before_script:
  - echo 'Europe/Dublin' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata
      
after_failure:
    - "./data/travis-ci/after_failure.sh"

